### ISSUE TITLE
[feature] lazy attribute rendering + form fill

### ISSUE THREAD

**Issue by raisjn** [pelme/htpy#67] opened 2024-11-27 05:12 UTC
1. Is it possible to return the element tree without the attributes filled out? It's common that I want to add a class or ID after the fact to an element. I commonly generate a wrapper div with a unique class because I don't access the original element's attributes - it could be I'm not understanding how to handle this use case properly. 
2. I also think that another common use case would be something similar to fasthtml's [fill_form](https://docs.fastht.ml/api/components.html#fill_form)

**Comment by raisjn** [comment] 2024-11-27 10:51
for 1: 

let's say I want to run some JS on the page and pass an element to the JS. in this case, i want to know the selector for the element. 

what I would like to do:

```python
el = render_some_content(...);
selector = determine_class(el);
run_javascript("console.log", selector);
run_javascript("document.querySelector", selector);

```

what i currently do:

```python
def wrap_element(el):
    selector = generate_unique_class();
    return selector, div(class_=[selector])[el];
    
el = render_some_content(...);
selector, el = wrap_element(el);
run_javascript("console.log", selector)
run_javascript("document.querySelector", selector)
```

for 2:

do you want code for this? or are the docs enough?

**Comment by pelme** [comment] 2024-11-27 19:01
1. All elements in htpy are immutable (just like in JSX/React). You cannot really change an element once it is created, this is by design. This makes it possible to use the same element in multiple places without having the risk of it changing in an unexpected way.

If you do not want a wrapping div around your element, I would suggest that you make it possible to set the class/selector on render_some_content(). That way, just looking at the code you can see that they reference the same selector and you have no surprises from mutable objects>

```py
selector = generate_unique_class()
el = render_some_content(..., selector=selector)
run_javascript("console.log", selector)
run_javascript("document.querySelector", selector)
```

2. htpy just tries to render html elements and not much more. You can certainly build a function like fill_form or a system to generate html forms with htpy if you like.
 
Displaying forms with predefined values, validation errors, help texts, labels, layouts etc is a complex problem and I can see fill_form fills (setting value to fields from python attributes) a very small piece of that.

I have built everything from trivial forms to huge complex forms with htpy, mainly using `django.forms` ([see this example](https://htpy.dev/django/#render-a-django-form)). There are also libraries such as https://django-floppyforms.readthedocs.io/en/latest/  and https://wtforms.readthedocs.io/en/3.2.x/ that renders the fields and also has a bunch of nice widgets, validation etc.

If someone is interested, building a set of django widgets or wtforms widgets in htpy would be straightforward and publishing them as a package would be possible. It would also be possible to create a full forms library built on top of htpy rendering.

**Comment by raisjn** [comment] 2024-11-27 19:09
thanks for the explanations!

> All elements in htpy are immutable (just like in JSX/React). You cannot really change an element once it is created, this is by design. This makes it possible to use the same element in multiple places without having the risk of it changing in an unexpected way

is there a reference to this in the docs? i saw it was inspired by react, but didn't realize about the immutability portion except when i read the code and saw that everything is generated as a string upon creation

> I have built everything from trivial forms to huge complex forms with htpy, mainly using django.forms

thanks, i'll look at these examples. i'm not using django (just fastAPI + pydantic), will see what they have in common.

**Comment by pelme** [comment] 2024-12-15 19:20
Thanks for the suggestion about immutability, I have added it to the docs now:
https://htpy.dev/common-patterns/#creating-components

I hope it makes it clearer going forward!

Closing this issue now, feel free to reopen or open another issue if you have any ideas/suggestions!

**Closed by pelme** 2024-12-15 19:20 UTC
